### 5.7.산술 연산

- for 문장 없이 데이터를 일괄 처리하여 연산 가능

- 같은 크기의 배열 간의 산술 연산은 배열의 각 원소 단위로 적용됨


Q1. 다음의 행렬을 a 변수에 입력하고 a*a, a-a, 1/a, a**0.5 값을 확인하라.
 
 $$\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}$$

In [1]:
import numpy as np
a=np.arange(1,7).reshape(-1,3)
#a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [2]:
a*a # 각 원소의 곱

array([[ 1,  4,  9],
       [16, 25, 36]])

In [3]:
a-a # 각 원소의 차

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
1/a #각 원소의 역분수

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [5]:
a*0.5

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ]])

In [6]:
a**0.5 # 각 원소의 sqrt

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Q2.아래 2개의 행렬을 x1, y1변수에 입력하고, x1+y1, x1-y1, x1/y1 x1*y1 값을 확인하라.

$$\begin{bmatrix} 
 1 & 1  \\
3 & 3 
\end{bmatrix}$$

$$\begin{bmatrix} 
3 & 1 \\
3 & 1 
\end{bmatrix}$$


In [7]:
x1 = np.array([[1,1], [3,3]])
y1 = np.array([[3,1], [3,1]])
print(x1)
print(y1)

[[1 1]
 [3 3]]
[[3 1]
 [3 1]]


In [8]:
x1+y1

array([[4, 2],
       [6, 4]])

In [9]:
x1-y1

array([[-2,  0],
       [ 0,  2]])

In [10]:
x1/y1

array([[0.33333333, 1.        ],
       [1.        , 3.        ]])

In [11]:
x1*y1

array([[3, 1],
       [9, 3]])

- 브로드캐스팅 : 크기가 다른 배열간의 연산

  1. 상수항의 연산
  2. (row,column) 행렬과 벡터간의 연산
  3. (row,column) 행렬과 (row,1) 행렬간의 연산

Q3. 아래 행렬을 x1에 입력하고, 상수항 4를 더하고, 빼고, 곱하고, 나누고, 4만큼 제곱승 해보아라.


$$\begin{bmatrix} 
 1 & 1  \\
 3 & 3  
\end{bmatrix}$$


In [12]:
x1 = np.array([[1,1], [3,3]])
s=4 
x1+s # 모든 원소에 스칼라 만큼 더하기

array([[5, 5],
       [7, 7]])

In [13]:
x1-s # 모든 원소에 스칼라 만큼 빼기

array([[-3, -3],
       [-1, -1]])

In [14]:
x1*s # 모든 원소에 스칼라 만큼 곱하기

array([[ 4,  4],
       [12, 12]])

In [15]:
x1/s # 모든 원소에 스칼라 만큼 나누기

array([[0.25, 0.25],
       [0.75, 0.75]])

In [16]:
x1**s # 모든 원소에 스칼라 만큼 제곱승 하기

array([[ 1,  1],
       [81, 81]])

Q3. 아래 행렬을 x1과 y1에 입력하고, x1+y1, x1-y1, x1*y1을 계산해 보아라.

$$\begin{bmatrix} 
 1 & 1  \\
 3 & 3  
\end{bmatrix}$$

$$\begin{bmatrix} 
  2 & 3  
\end{bmatrix}$$


In [17]:
x1 = np.array([[1,1], [3,3]])
y1 = np.array([2,3])

In [18]:
x1.shape #(2,2) 행렬

(2, 2)

In [19]:
y1.shape  #(2,) 로 원소 2개인 원소

(2,)

In [20]:
x1+y1 # 벡터인 y1이 x1의 row 개수 만큼 있다고 가정하에 연산을 함
      # 즉, array([[1, 1],   과 array([[2, 3],   의 연산을 함
      #           [3, 3]])             [2, 3]]) 

array([[3, 4],
       [5, 6]])

In [21]:
x1-y1

array([[-1, -2],
       [ 1,  0]])

In [22]:
x1*y1

array([[2, 3],
       [6, 9]])

Q4. 아래 행렬을 x1과 y1에 입력하고, x1+y1, x1-y1, x1*y1 을 계산해 보아라.

$$\begin{bmatrix}
 1 & 1  \\
 3 & 3  
\end{bmatrix}$$

$$\begin{bmatrix} 
  2 \\
   3 
\end{bmatrix}$$

In [23]:
x1 = np.array([[1,1], [3,3]])
y1 = np.array([[2],[3]])

In [24]:
y1.shape   #(2,1) 행렬

(2, 1)

In [25]:
x1+y1 #  column이 한개인 행렬 y1이 x1의 column 개수 만큼 있다고 가정하에 연산을 함
      # 즉, array([[1, 1],   과 array([[2, 2],   의 연산을 함
      #           [3, 3]])             [3, 3]]) 

array([[3, 3],
       [6, 6]])

In [26]:
x1-y1

array([[-1, -1],
       [ 0,  0]])

In [27]:
x1*y1

array([[2, 2],
       [9, 9]])

- 선형대수 

  1. T (or transpose) : 전치행렬
  2. dot ( or @) : 행렬곱셈
  $ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$
  3. inv : 역행렬 (numpy.linalg)
  4. solve : A가 정사각 행렬일 때 , Ax=b를 만족하는 x를 구하는 함수 (numpy.linalg)
  5. det : 행렬식 (numpy.linalg) 
  
  
- numpy.linalg 는 행렬의 분할과 역행렬, 행렬식과 같은 것들을 포함하고 있음.

  np.linalg.inv, np.linalg.solve, np.linalg.det

Q5. 아래 행렬을 x변수에 입력하고, 전치행렬을 만들어라.
 
$$\begin{bmatrix} 
 1 & 2  \\
 3 & 4  
\end{bmatrix}$$

In [28]:
x = np.array([[1,2], [3,4]])
x

array([[1, 2],
       [3, 4]])

In [29]:
x.T   #전치행렬

array([[1, 3],
       [2, 4]])

In [30]:
x.transpose()

array([[1, 3],
       [2, 4]])

Q6. X'X 행렬 곱셈을 해보아라.

In [31]:
x.T.dot(x) # X'X 행렬 곱셈

array([[10, 14],
       [14, 20]])

In [32]:
np.dot(x.T, x)

array([[10, 14],
       [14, 20]])

In [33]:
x.T @ x

array([[10, 14],
       [14, 20]])

Q6.$ (X'X)^{-1} $ 를 구하여라.

In [34]:
inv_x=np.linalg.inv(x.T@x)  # inv 함수는 numpy.linalg에 있음.
inv_x

array([[ 5. , -3.5],
       [-3.5,  2.5]])

Q7. 다음식의 해 x,y를 구하여라.

 $ \begin{bmatrix}3 \ 1\\
 1 \ 2 \end{bmatrix}
\cdot
\begin{bmatrix}x \\ y\end{bmatrix}
= \begin{bmatrix}9 \\ 8\end{bmatrix}$

In [35]:
a = np.array([[3,1], [1,2]])
b = np.array([[9],[8]])
x = np.linalg.solve(a,b)
x

array([[2.],
       [3.]])

Q8.다음 행렬의 행렬식을 구하여라. 

 $ \begin{bmatrix}3 \ 1\\
 1 \ 2 \end{bmatrix}$

In [36]:
a = np.array([[3,1], [1,2]])
np.linalg.det(a)  #ad-bc 의 값

5.000000000000001

- Q) 다음의 array를 각 원소별로 5로 나눴을 때 나머지로 이루어진 array를 찾아라.

[0, 1, 2, 3, 4 ,5 ,6]

In [38]:
a = np.array([0, 1, 2, 3, 4 ,5 ,6])
a % 5

array([0, 1, 2, 3, 4, 0, 1])

- Q) 다음의 array의 각 원소들의 절대값으로 이루어진 array를 찾아라. 힌트) 절대값 함수 : abs(x) 
    
[-1.4,  2.0 ]

In [39]:
a = np.array([-1.4,2.0])
abs(a)

array([1.4, 2. ])

- Q) 다음의 array X,Y,Z에 대하여 X+Y와 X-Z의 결과값이 무엇일지 프로그램을 돌리기 전에 알아보아라.

 
 $ X=\begin{bmatrix} 0 \ 1 \ 2 \\
 3 \ 4 \ 5 \\ 
 6 \ 7 \ 8 \\ 
 9 \ 10 \ 11 \end{bmatrix}$

$ Y=\begin{bmatrix} 10 \ 11 \ 12 \end{bmatrix}$


$ Z=\begin{bmatrix} 10 \\ 11 \\ 12 \\ 13 \end{bmatrix}$

 

In [42]:
X = np.arange(0,12).reshape((4,3))
Y = np.arange(10,13).reshape((1,3))
Z = np.arange(10,14).reshape((4,1))

print(X)
print(Y)
print(Z)

print(X+Y)
print(X-Z)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[10 11 12]]
[[10]
 [11]
 [12]
 [13]]
[[10 12 14]
 [13 15 17]
 [16 18 20]
 [19 21 23]]
[[-10  -9  -8]
 [ -8  -7  -6]
 [ -6  -5  -4]
 [ -4  -3  -2]]


- Q) 2개의 미지수로 되어 있는 다음 2개식의 해를 구하시오.

 2X+3Y=6                         
 X-4Y=2
 
 

In [43]:
a = np.array([[2,3],[1,-4]])
b=np.array([[6],[2]])
np.linalg.solve(a,b)

array([[2.72727273],
       [0.18181818]])