## 5. Numpy

   - 패키지로 Numerical Python의 줄임말
   
   - Numpy가 제공하는 것들
   
     1. 다차원 배열(ndarray)객체를 다룸 : 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조
     2. 반복문 필요없이 전체 데이터 배열을 빠르게 계산할 수 있는 표준 수학 함수
     3. 선형대수, 난수 생성기, 푸리에 변환 가능
  
  
   - Install : cmd에서 pip install numpy 
  
  
   - import 사용하여 numpy 불러오기
   
     import numpy : numpy.array 로 사용
     
     import numpy as np  : np.array로 사용

In [3]:
import numpy

numpy.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
import numpy as np

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

### 5.1. arange 함수

- range 함수의 배열 버전

- arange([start],stop,[step],dtype=None)

- start : default는 0 

  step : default는 1, step이 다른값이 쓰여지면 start도 반드시 값이 주어져야 함.
  
  dtype : 데이타 type을 의미함.  
  
  * float도 가능

Q1. 0~14의 정수배열을 만들고 type을 확인하시오.

In [5]:
a=np.arange(15) # 0~(15-1)까지 step =1
print(a , a.dtype  )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] int32


In [6]:
type(a)

numpy.ndarray

Q2. 시작점 2, 끝점 8까지 step은 2씩 증가하는 배열을 만들어라.

In [10]:
a=np.arange(2,10,2) # 시작점 2부터 끝점 10보다 작은 숫자까지
a

array([ 2,  4,  6,  8, 10])

Q3. 시작점 0.1, 끝점 0.9, step은 0.1씩 증가하는 배열을 만들어라.

In [11]:
a=np.arange(0.1, 1.0, 0.1) # 시작점 0.1, 끝점 1.0보다 작은 숫자까지 , step 0.1씩 증가
a

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [12]:
a=np.arange(0.1,1.0,0.2)
a

array([0.1, 0.3, 0.5, 0.7, 0.9])

In [13]:
a.dtype

dtype('float64')

Q4. 위 Q3의 type을 int형으로 바꿔라.

In [14]:
a=np.arange(0.1, 1.0, 0.1,dtype='i')  # 정수형으로 바뀜 dtype='int'
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [15]:
a=np.arange(0.1, 1.0, 0.1)  
b=np.int32(a)
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [16]:
b=a.astype('int')
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
#a=np.arange(0,2,dtype='<U32')  #문자형
#a

TypeError: arange() not supported for inputs with DType <class 'numpy.dtype[str_]'>.

Q5. 0~14의 정수배열을 만들고, 행x열 크기가 3x5인 행열로 만들어라.

In [18]:
a=np.arange(15)
b=a.reshape(3,5) #배열의 모양을 변환, reshape(row, column)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [19]:
c=a.reshape(-1,5) # "-1"을 사용하면 column=5인 상태에서 row을 알아서 정해줌
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
d=a.reshape(5,-1) # "-1"을 사용하면 row=5인 상태에서 column을 알아서 정해줌
d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### 5.2. ndarray 의 속성

- ndim : 행렬의 dimension 수

- shape : 행렬의 dimension을 나타내는 튜플형 ex) ndim=2인 경우 (row, column)

- size :  원소 수 = shape의 dimension 곱

- dtype : 데이타 type 

        cf) 리스트형은 서로 다른 데이터 타입을 가질 수 있으나, ndarray는 같은 데이터 타입만 가능함. 
            ndarray에서 string > float > int 순서임.

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
a.ndim

1

In [27]:
a.shape

(15,)

In [28]:
a.size

15

In [29]:
a.dtype

dtype('int32')

In [30]:
l=[1,1.5,'s'] # 리스트형은 서로 다른 데이터 타입 가능
print(l)
print(type(l[0]), type(l[1]), type(l[2]))

[1, 1.5, 's']
<class 'int'> <class 'float'> <class 'str'>


In [32]:
da=np.array([1,1.5 ]) #ndarray는 같은 데이터 타입만 가능함
print(da)
print(type(da[0]), type(da[1]) )

[1.  1.5]
<class 'numpy.float64'> <class 'numpy.float64'>


### 5.3.array 함수

- 배열을 생성하는 가장 쉬운 방법

- 순차적인 객체를 넘겨 받고, 넘겨 받은 데이터가 들어 있는 새로운 Numpy 배열을 생성함.

- 리스트를 담고 있는 리스트는 해당 데이터로부터 형태를 추론하여 n차원 형태로 생성됨.
 

Q6.리스트 형식으로 [6,7.5,8,0,1,1] 를 data1에 입력하고 배열로 변환하라.

In [33]:
data1=[6,7.5,8,0,1,1] # 리스트형식
a=np.array(data1) 
a 

array([6. , 7.5, 8. , 0. , 1. , 1. ])

In [34]:
a.dtype

dtype('float64')

In [35]:
np.array([6,7.5,8,0,1,1] ) # 직접 입력

array([6. , 7.5, 8. , 0. , 1. , 1. ])

Q7.[ [1,2,3,4] , [5,6,7,8]] 리스트 자료형을 배열로 변환하여 2x4 행렬이 됨을 확인하라.

In [37]:
data2=[ [1,2,3,4] , [5,6,7,8]]
a=np.array(data2)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
a.ndim

2

In [39]:
a.shape

(2, 4)

Q8. [ [[1,2],[3,4]] , [[5,6],[7,8]]] 리스트 자료형을 배열로 변환하여 2x2x2 행렬이 됨을 확인하라.

In [40]:
data2=[ [[1,2],[3,4]] , [[5,6],[7,8]] , [[5,6],[7,8]] ]
a=np.array(data2)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[5, 6],
        [7, 8]]])

In [41]:
a.ndim

3

In [42]:
a.shape

(3, 2, 2)

Q9.위 Q6,Q7,Q8의 자료를 튜플형식으로 입력하여 배열로 전환하라. 

In [36]:
data1=(6,7.5,8,0,1,1) # 튜플형식
a=np.array(data1) 
a

array([6. , 7.5, 8. , 0. , 1. , 1. ])

In [43]:
data2=( (1,2,3,4) , (5,6,7,8)) 
a=np.array(data2)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
data2=( ((1,2),(3,4)) , ((5,6),(7,8)))
a=np.array(data2)
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [45]:
np.array(6,7.5,8,0,1,1) #Error

TypeError: array() takes from 1 to 2 positional arguments but 6 were given

In [46]:
np.array((6,7.5,8,0,1,1))

array([6. , 7.5, 8. , 0. , 1. , 1. ])

### 5.4.행렬의 정렬

- np.sort(ndarray) : 원본 행렬은 그대로 유지하고, 정렬된 행렬을 반환 
             np.sort(행렬, axis=0|1) axis=0은 row 방향 정렬(column fix), axis=1은 column 방향 정렬(row fix)
- ndarray.sort() : 원본 행렬 자체를 정렬한 형태로 변환
- np.argsort() : 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환

Q10. [3,1,9,5]를 1차원 array로 만들고, 오름차순, 내림차순으로 각각 정렬해 보아라.

In [47]:
org_a=np.array([3,1,9,5])
print(np.sort(org_a )) # 오름차순
print(np.sort(org_a)[::-1]) #내림차순
print(org_a)

[1 3 5 9]
[9 5 3 1]
[3 1 9 5]


In [48]:
org_b=org_a.copy()
print(org_b.sort())# 오름차순 ,반환되는 value는 None
print(org_b)       # org_b 자체가 변경됨
print(org_b[::-1].sort()) # 내림차순 
print(org_b) 

None
[1 3 5 9]
None
[9 5 3 1]


In [50]:
sorted(org_a,reverse=True)

[9, 5, 3, 1]

In [51]:
a_list=[1,4,0,6]
print(a_list[::-1])
print(a_list)
print(sorted(a_list,reverse=True)) #sorted 내림차순
print(sorted(a_list)[::-1]) #sorted 내림차순(오름차순 한 후 reverse)

[6, 0, 4, 1]
[1, 4, 0, 6]
[6, 4, 1, 0]
[6, 4, 1, 0]


Q11. 위 Q10의 정렬을 원본 array의 index를 이용하여 표현하라.

In [52]:
org_a

array([3, 1, 9, 5])

In [53]:
index_org=np.argsort(org_a) #[3,1,9,5] 의 오름차순 정렬을 원본 index로 표현
print(index_org)

[1 0 3 2]


In [56]:
index_org=np.argsort(org_a)[::-1] #[3,1,9,5] 의 내림차순 정렬을 원본 index로 표현
print(index_org)

[2 3 0 1]


In [55]:
org_a

array([3, 1, 9, 5])

In [57]:
org_a[index_org]

array([9, 5, 3, 1])

Q12. 2차원 array의 예제로 정렬해 보고, index로 표현해 보아라.

In [58]:
org_a=np.array([8,12,10,9,1,2]).reshape(3,-1)
org_a

array([[ 8, 12],
       [10,  9],
       [ 1,  2]])

In [59]:
print(np.sort(org_a,axis=0)) #row 방향
print(np.sort(org_a,axis=1)) #column 방향

[[ 1  2]
 [ 8  9]
 [10 12]]
[[ 8 12]
 [ 9 10]
 [ 1  2]]


In [60]:
org_a=np.array([8,12,10,9,1,2]).reshape(3,-1)
print(org_a)
print(org_a.sort(axis=0))
print(org_a)

[[ 8 12]
 [10  9]
 [ 1  2]]
None
[[ 1  2]
 [ 8  9]
 [10 12]]


In [61]:
org_a=np.array([8,12,10,9,1,2]).reshape(3,-1)
print(org_a)
print(org_a.sort(axis=1))
print(org_a)

[[ 8 12]
 [10  9]
 [ 1  2]]
None
[[ 8 12]
 [ 9 10]
 [ 1  2]]


### 5.5.zeros 함수

- 모든 원소가 0인 행렬

- zeros(shape,dtype)  : dtype 의 default는 float

Q13. 5개의 원소값이 0인 배열을 만들어라.

In [ ]:
np.zeros(5)

Q14. 2x4의 행렬로 모든 원소가 0인 행렬을 만들어라.

In [ ]:
a=np.zeros((2,4))  #shape (2,4)인 행렬
a

Q15. 위 Q14의 문제의 type을 확인하고, int형 zero 행렬을 만들어라. 

In [ ]:
print(a.dtype)
b=np.zeros((2,4),dtype=int) #int32 형
print(b)
print(b.dtype)

### 5.6.ones 함수

- 모든 원소가 1인 행렬

- ones(shape,dtype) : dtype 의 default는 float

In [ ]:
np.ones(5)

In [ ]:
np.ones((2,4))

In [ ]:
np.ones((2,4),dtype=int)

- Q) 다음과 같은 array가 만들어 지는 프로그램을 작성하라. (arange을 사용)

 $$\begin{array}{ccc}
[[2 & 3 & 4]\\
[5 & 6 & 7]\\
[8 &9 & 10]]
\end{array}$$

- Q) 다음과 같은 array가 만들어지는 프로그램을 작성하라. (arange을 사용)
 
 
 $$\begin{array}{ccccc}
[[0 & 2 & 4 & 6 & 8]\\
[10 & 12& 14&16&18]\\
[20 &22&24&26&28]]
\end{array}$$

- Q) 다음과 같은 array가 만들어지는 프로그램을 작성하라. 
 
 
 $$\begin{array}{ccccc}
[[2 & 2 & 2 & 2 & 2]\\
[2 & 2& 2&2&2]\\
[2 &2&2&2&2]]
\end{array}$$

- Q) 대각선외에는 0값, 대각선은 1또는 특정 수로 이루어진 array를 작성하려 한다. 힌트를 이용하여 다음과 같은 2개의 array를 만들기 위한 프로그램을 작성하라. 
 
$$\begin{array}{ccccc}
[[1 & 0 & 0 ]\\
[0 & 1& 0]\\
[0 & 0& 1]]
\end{array}$$


$$\begin{array}{ccccc}
[[4 & 0 & 0 ]\\
[0 & 5& 0]\\
[0 & 0& 6]]
\end{array}$$

   힌트) eye(n) : nxn array의 대각선값은 1, 이외는 0
   
         diag(array) : array의 값을 대각선, 이외는 0
         

- Q) 학생별 시험성적을 2개의 ndarray를 이용하여 다음과 같이 입력하고, 시험성적순으로 학생이름을 출력해 보아라.

     name_array=np.array(['John','Mike','Sarah','Kate','Samuel'])
     
     score_array=np.array([78,95,84,98,88])

- Q) 1부터 10까지 숫자로 이루어진 배열를 만든 뒤, 3,4,5,6,7,8의 숫자에 대해서는 마이너스(-)을 붙여 다음과 같은 배열을 만들어라. 

[ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10]

   단, index를 사용하지 말고 3보다 크거나 같고, 8보다 작거나 같다의 부등호를 사용하라.